---

server:
  port: 8000
  servlet:
    context-path: /cust-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case_study?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ddl-auto: update
