---

server:
  port: 9000
  servlet:
    context-path: /item-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case_study?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ddl-auto: update
